name: Release Automation

on:
    pull_request:
        types:
            - closed
        branches:
            - v2.x

jobs:
    tag_release:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Read Version from Laravel Config
              run: |
                  VERSION=$(php -r "echo json_decode(json_encode(include 'config/version.php'))->version;")
                  echo "VERSION=$VERSION" >> $GITHUB_ENV
                  echo "Extracted version: $VERSION"

            - name: Configure Git User
              run: |
                  git config --local user.email "github-actions@github.com"
                  git config --local user.name "GitHub Actions"

            - name: Create Version Tag
              run: |
                  git tag -a "v$VERSION" -m "New Release: v$VERSION"
                  git push origin "v$VERSION"
